# src/main/resources/application.yml

server:
  port: 8080
  error:
    include-message: NEVER         # Production: never leak error messages in responses
    include-stacktrace: NEVER      # Production: never include stack traces in responses
  forward-headers-strategy: framework
  compression:
    enabled: true
    mime-types: application/json,text/html,text/plain,text/css,application/javascript

spring:
  profiles:
    active: dev
    group:
      prod: [mysql]
      dev: [mysql]                 # If you want dev to also run with MySQL
  jpa:
    open-in-view: false            # Best practice: disable Open Session in View
    properties:
      hibernate.jdbc.time_zone: UTC

app:
  security:
    jwt:
      issuer: slyther
      # In production: read from ENV: ${JWT_SECRET}
      secret: ${JWT_SECRET:CHANGE_ME_TO_A_LONG_RANDOM_SECRET_VALUE_256bit}
      access-exp-mins: 15
      refresh-exp-days: 14
    ratelimit:
      login:
        max-requests: 5
        window-seconds: 60
      forgot-password:
        max-requests: 5
        window-seconds: 60
  cors:
    allowed-origins:
      - "http://localhost:4200"
      - "http://localhost:3000"
      - "https://amir.ir"
    allowed-methods: [ GET, POST, PUT, DELETE, PATCH, OPTIONS ]



# Disable docs by default; enable them in dev profile
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true   # Enable readiness/liveness probes
